spring:
  profiles:
    active: live
    group:
      local: local_server, common, secret
      live: live_server, common, secret
      #blue: blue_server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server

server:
  port: 8080
#react:
#  server:
#    protocol: http
#    host: localhost
#    port: 3000

---
spring:
  config:
    activate:
      on-profile: live_server

server:
  port: 8080
#react:
#  server:
#    protocol: http
#    host: localhost
#    port: 3000

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 100MB #??? ??? ?? ?? ?? ??
      max-request-size: 1000MB #?? ? ??? ??? ?? ???? ?? ??

mybatis:
  mapper-locations:
    - /mappers/*.xml

springdoc:
  override-with-generic-response: false

server:
  forward-headers-strategy: native

schedule:
  cron: 0 0 0 * * *
  use: true
