spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret
      #blue: blue_server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server

server:
  port: 8080
react:
  server:
    protocol: http
    host: localhost
    port: 3000

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 100MB #??? ??? ?? ?? ?? ??
      max-request-size: 1000MB #?? ? ??? ??? ?? ???? ?? ??

mybatis:
  mapper-locations:
    - /mappers/*.xml